language: node_js
sudo: false
node_js:
- 12
- 14
- node
install:
- npm install
- npm install coveralls
script:
- npm run coverage
after_success:
- npm run coveralls
cache:
  directories:
    - node_modules
