
var Module = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  return (
function(Module) {
  Module = Module || {};

var aa,d;var h;h||(h=typeof Module !== 'undefined' ? Module : {});h.locateFile=function(a){return require?require("path").join(__dirname,a):a};var k={},l;for(l in h)h.hasOwnProperty(l)&&(k[l]=h[l]);h.arguments=[];h.thisProgram="./this.program";h.quit=function(a,b){throw b;};h.preRun=[];h.postRun=[];var m=!1,p=!1,q=!1,ba=!1;m="object"===typeof window;p="function"===typeof importScripts;q="object"===typeof process&&"function"===typeof require&&!m&&!p;ba=!m&&!q&&!p;
if(h.ENVIRONMENT)throw Error("Module.ENVIRONMENT has been deprecated. To force the environment, use the ENVIRONMENT compile-time option (for example, -s ENVIRONMENT=web or -s ENVIRONMENT=node)");var t="";
if(q){t=__dirname+"/";var ca,da;h.read=function(a,b){ca||(ca={});da||(da=require("path"));a=da.normalize(a);a=ca.readFileSync(a);return b?a:a.toString()};h.readBinary=function(a){a=h.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(h.thisProgram=process.argv[1].replace(/\\/g,"/"));h.arguments=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof ea))throw a;});process.on("unhandledRejection",u);h.quit=function(a){process.exit(a)};
h.inspect=function(){return"[Emscripten Module object]"}}else if(ba)"undefined"!=typeof read&&(h.read=function(a){return read(a)}),h.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?h.arguments=scriptArgs:"undefined"!=typeof arguments&&(h.arguments=arguments),"function"===typeof quit&&(h.quit=function(a){quit(a)});else if(m||p)p?t=self.location.href:document.currentScript&&
(t=document.currentScript.src),_scriptDir&&(t=_scriptDir),0!==t.indexOf("blob:")?t=t.substr(0,t.lastIndexOf("/")+1):t="",h.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},p&&(h.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),h.readAsync=function(a,b,c){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=function(){200==e.status||
0==e.status&&e.response?b(e.response):c()};e.onerror=c;e.send(null)},h.setWindowTitle=function(a){document.title=a};else throw Error("environment detection error");var fa=h.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),v=h.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||fa);for(l in k)k.hasOwnProperty(l)&&(h[l]=k[l]);k=void 0;
assert("undefined"===typeof h.memoryInitializerPrefixURL,"Module.memoryInitializerPrefixURL option was removed, use Module.locateFile instead");assert("undefined"===typeof h.pthreadMainPrefixURL,"Module.pthreadMainPrefixURL option was removed, use Module.locateFile instead");assert("undefined"===typeof h.cdInitializerPrefixURL,"Module.cdInitializerPrefixURL option was removed, use Module.locateFile instead");assert("undefined"===typeof h.filePackagePrefixURL,"Module.filePackagePrefixURL option was removed, use Module.locateFile instead");
ha=ja=ka=function(){u("cannot use the stack before compiled code is ready to run, and has provided stack access")};function la(a){assert(w);var b=x[w>>2];a=b+a+15&-16;if(a<=ma())x[w>>2]=a;else return 0;return b}function na(a){oa||(oa={});oa[a]||(oa[a]=1,v(a))}var oa,pa={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},y=Array(30);"object"!==typeof WebAssembly&&u("No WebAssembly support found. Build with -s WASM=0 to target JavaScript instead.");var qa,ra=!1;
function assert(a,b){a||u("Assertion failed: "+b)}function sa(a){var b=h["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function ta(a,b,c,e){var f={string:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var c=(a.length<<2)+1,e=b=ka(c);assert("number"==typeof c,"stringToUTF8(str, outPtr, maxBytesToWrite) is missing the third parameter that specifies the length of the output buffer!");ua(a,A,e,c)}return b},array:function(a){var b=ka(a.length);assert(0<=a.length,"writeArrayToMemory array must have a length (should be an array or typed array)");B.set(a,b);return b}},g=sa(a),n=[];a=0;assert("array"!==b,'Return type should not be "array".');
if(e)for(var r=0;r<e.length;r++){var z=f[c[r]];z?(0===a&&(a=ha()),n[r]=z(e[r])):n[r]=e[r]}c=g.apply(null,n);c=function(a){return"string"===b?C(a):"boolean"===b?!!a:a}(c);0!==a&&ja(a);return c}var va="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function D(a,b,c){var e=b+c;for(c=b;a[c]&&!(c>=e);)++c;if(16<c-b&&a.subarray&&va)return va.decode(a.subarray(b,c));for(e="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|g);else{var n=a[b++]&63;224==(f&240)?f=(f&15)<<12|g<<6|n:(240!=(f&248)&&na("Invalid UTF-8 leading byte 0x"+f.toString(16)+" encountered when deserializing a UTF-8 string on the asm.js/wasm heap to a JS string!"),f=(f&7)<<18|g<<12|n<<6|a[b++]&63);65536>f?e+=String.fromCharCode(f):(f-=
65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e}function C(a,b){return a?D(A,a,b):""}
function ua(a,b,c,e){if(!(0<e))return 0;var f=c;e=c+e-1;for(var g=0;g<a.length;++g){var n=a.charCodeAt(g);if(55296<=n&&57343>=n){var r=a.charCodeAt(++g);n=65536+((n&1023)<<10)|r&1023}if(127>=n){if(c>=e)break;b[c++]=n}else{if(2047>=n){if(c+1>=e)break;b[c++]=192|n>>6}else{if(65535>=n){if(c+2>=e)break;b[c++]=224|n>>12}else{if(c+3>=e)break;2097152<=n&&na("Invalid Unicode code point 0x"+n.toString(16)+" encountered when serializing a JS string to an UTF-8 string on the asm.js/wasm heap! (Valid unicode code points should be in range 0-0x1FFFFF).");
b[c++]=240|n>>18;b[c++]=128|n>>12&63}b[c++]=128|n>>6&63}b[c++]=128|n&63}}b[c]=0;return c-f}function wa(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");
function xa(a){return a.replace(/__Z[\w\d_]+/g,function(a){na("warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling");return a===a?a:a+" ["+a+"]"})}function ya(){a:{var a=Error();if(!a.stack){try{throw Error(0);}catch(b){a=b}if(!a.stack){a="(no stack trace available)";break a}}a=a.stack.toString()}h.extraStackTrace&&(a+="\n"+h.extraStackTrace());return xa(a)}var buffer,B,A,za,x,E,w=12864;assert(!0,"stack must start aligned");assert(!0,"heap must start aligned");
h.TOTAL_STACK&&assert(5242880===h.TOTAL_STACK,"the stack size can no longer be determined at runtime");var F=h.TOTAL_MEMORY||16777216;5242880>F&&v("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+F+"! (TOTAL_STACK=5242880)");assert("undefined"!==typeof Int32Array&&"undefined"!==typeof Float64Array&&void 0!==Int32Array.prototype.subarray&&void 0!==Int32Array.prototype.set,"JS engine does not provide full typed array support");
h.buffer?(buffer=h.buffer,assert(buffer.byteLength===F,"provided buffer should be "+F+" bytes, but it is "+buffer.byteLength)):("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(assert(0===F%65536),qa=new WebAssembly.Memory({initial:F/65536,maximum:F/65536}),buffer=qa.buffer):buffer=new ArrayBuffer(F),assert(buffer.byteLength===F));h.HEAP8=B=new Int8Array(buffer);h.HEAP16=za=new Int16Array(buffer);h.HEAP32=x=new Int32Array(buffer);h.HEAPU8=A=new Uint8Array(buffer);h.HEAPU16=new Uint16Array(buffer);
h.HEAPU32=E=new Uint32Array(buffer);h.HEAPF32=new Float32Array(buffer);h.HEAPF64=new Float64Array(buffer);x[w>>2]=5255776;function Aa(){34821223==E[1313943]&&2310721022==E[1313942]||u("Stack overflow! Stack cookie has been overwritten, expected hex dwords 0x89BACDFE and 0x02135467, but received 0x"+E[1313942].toString(16)+" "+E[1313943].toString(16));if(1668509029!==x[0])throw"Runtime error: The application has corrupted its heap memory area (address zero)!";}x[0]=1668509029;za[1]=25459;
if(115!==A[2]||99!==A[3])throw"Runtime error: expected the system to be little-endian!";function Ba(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.Bb;"number"===typeof c?void 0===b.gb?h.dynCall_v(c):h.dynCall_vi(c,b.gb):c(void 0===b.gb?null:b.gb)}}}var Ca=[],Da=[],Fa=[],Ga=[],G=!1;function Ha(){var a=h.preRun.shift();Ca.unshift(a)}assert(Math.imul,"This browser does not support Math.imul(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");
assert(Math.fround,"This browser does not support Math.fround(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");assert(Math.clz32,"This browser does not support Math.clz32(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");assert(Math.trunc,"This browser does not support Math.trunc(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");
var Ia=Math.abs,Ja=Math.ceil,Ka=Math.floor,La=Math.min,H=0,I=null,J=null,K={};function Ma(){H++;h.monitorRunDependencies&&h.monitorRunDependencies(H);assert(!K["wasm-instantiate"]);K["wasm-instantiate"]=1;null===I&&"undefined"!==typeof setInterval&&(I=setInterval(function(){if(ra)clearInterval(I),I=null;else{var a=!1,b;for(b in K)a||(a=!0,v("still waiting on run dependencies:")),v("dependency: "+b);a&&v("(end of list)")}},1E4))}h.preloadedImages={};h.preloadedAudios={};
function Na(){var a=L;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var L="expat.wasm";if(!Na()){var Oa=L;L=h.locateFile?h.locateFile(Oa,t):t+Oa}function Pa(){try{if(h.wasmBinary)return new Uint8Array(h.wasmBinary);if(h.readBinary)return h.readBinary(L);throw"both async and sync fetching of the wasm failed";}catch(a){u(a)}}
function Qa(){return h.wasmBinary||!m&&!p||"function"!==typeof fetch?new Promise(function(a){a(Pa())}):fetch(L,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+L+"'";return a.arrayBuffer()}).catch(function(){return Pa()})}
function Ra(a){function b(a){h.asm=a.exports;H--;h.monitorRunDependencies&&h.monitorRunDependencies(H);assert(K["wasm-instantiate"]);delete K["wasm-instantiate"];0==H&&(null!==I&&(clearInterval(I),I=null),J&&(a=J,J=null,a()))}function c(a){assert(h===g,"the Module object should not be replaced during async compilation - perhaps the order of HTML elements is wrong?");g=null;b(a.instance)}function e(a){Qa().then(function(a){return WebAssembly.instantiate(a,f)}).then(a,function(a){v("failed to asynchronously prepare wasm: "+
a);u(a)})}var f={env:a,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:pa};Ma();if(h.instantiateWasm)try{return h.instantiateWasm(f,b)}catch(n){return v("Module.instantiateWasm callback failed with error: "+n),!1}var g=h;h.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||Na()||"function"!==typeof fetch?e(c):WebAssembly.instantiateStreaming(fetch(L,{credentials:"same-origin"}),f).then(c,function(a){v("wasm streaming compile failed: "+a);v("falling back to ArrayBuffer instantiation");
e(c)});return{}}h.asm=function(a,b){b.memory=qa;b.table=new WebAssembly.Table({initial:800,maximum:800,element:"anyfunc"});b.__memory_base=1024;b.__table_base=0;a=Ra(b);assert(a,"binaryen setup failed (no wasm support?)");return a};Da.push({Bb:function(){Sa()}});assert(!0);var M={};
function Ta(a){if(Ta.$a){var b=x[a>>2];var c=x[b>>2]}else Ta.$a=!0,M.USER=M.LOGNAME="web_user",M.PATH="/",M.PWD="/",M.HOME="/home/web_user",M.LANG="C.UTF-8",M._=h.thisProgram,c=G?Ua(1024):la(1024),b=G?Ua(256):la(256),x[b>>2]=c,x[a>>2]=b;a=[];var e=0,f;for(f in M)if("string"===typeof M[f]){var g=f+"="+M[f];a.push(g);e+=g.length}if(1024<e)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(f=0;f<a.length;f++){e=g=a[f];for(var n=c,r=0;r<e.length;++r)assert(e.charCodeAt(r)===e.charCodeAt(r)&
255),B[n++>>0]=e.charCodeAt(r);B[n>>0]=0;x[b+4*f>>2]=c;c+=g.length+1}x[b+4*a.length>>2]=0}function Va(a,b){for(var c=0,e=a.length-1;0<=e;e--){var f=a[e];"."===f?a.splice(e,1):".."===f?(a.splice(e,1),c++):c&&(a.splice(e,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Xa(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Va(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Ya(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Za(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function $a(){var a=Array.prototype.slice.call(arguments,0);return Xa(a.join("/"))}function N(a,b){return Xa(a+"/"+b)}
function ab(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Va(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var bb=[];function cb(a,b){bb[a]={input:[],output:[],ab:b};db(a,eb)}
var eb={open:function(a){var b=bb[a.node.rdev];if(!b)throw new O(19);a.tty=b;a.seekable=!1},close:function(a){a.tty.ab.flush(a.tty)},flush:function(a){a.tty.ab.flush(a.tty)},read:function(a,b,c,e){if(!a.tty||!a.tty.ab.tb)throw new O(6);for(var f=0,g=0;g<e;g++){try{var n=a.tty.ab.tb(a.tty)}catch(r){throw new O(5);}if(void 0===n&&0===f)throw new O(11);if(null===n||void 0===n)break;f++;b[c+g]=n}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,e){if(!a.tty||!a.tty.ab.jb)throw new O(6);
try{for(var f=0;f<e;f++)a.tty.ab.jb(a.tty,b[c+f])}catch(g){throw new O(5);}e&&(a.node.timestamp=Date.now());return f}},fb={tb:function(a){if(!a.input.length){var b=null;if(q){var c=new Buffer(256),e=0,f=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{f=fs.openSync("/dev/stdin","r"),g=!0}catch(n){}}try{e=fs.readSync(f,c,0,256,null)}catch(n){if(-1!=n.toString().indexOf("EOF"))e=0;else throw n;}g&&fs.closeSync(f);0<e?b=c.slice(0,e).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;c=Array(wa(b)+1);b=ua(b,c,0,c.length);c.length=b;a.input=c}return a.input.shift()},jb:function(a,b){null===b||10===b?(fa(D(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(fa(D(a.output,0)),a.output=[])}},gb={jb:function(a,b){null===b||10===b?(v(D(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},
flush:function(a){a.output&&0<a.output.length&&(v(D(a.output,0)),a.output=[])}},P={Va:null,Sa:function(){return P.createNode(null,"/",16895,0)},createNode:function(a,b,c,e){if(24576===(c&61440)||4096===(c&61440))throw new O(1);P.Va||(P.Va={dir:{node:{Wa:P.Oa.Wa,Ua:P.Oa.Ua,lookup:P.Oa.lookup,bb:P.Oa.bb,rename:P.Oa.rename,unlink:P.Oa.unlink,rmdir:P.Oa.rmdir,readdir:P.Oa.readdir,symlink:P.Oa.symlink},stream:{Xa:P.Pa.Xa}},file:{node:{Wa:P.Oa.Wa,Ua:P.Oa.Ua},stream:{Xa:P.Pa.Xa,read:P.Pa.read,write:P.Pa.write,
lb:P.Pa.lb,ub:P.Pa.ub,wb:P.Pa.wb}},link:{node:{Wa:P.Oa.Wa,Ua:P.Oa.Ua,readlink:P.Oa.readlink},stream:{}},nb:{node:{Wa:P.Oa.Wa,Ua:P.Oa.Ua},stream:hb}});c=ib(a,b,c,e);16384===(c.mode&61440)?(c.Oa=P.Va.dir.node,c.Pa=P.Va.dir.stream,c.Na={}):32768===(c.mode&61440)?(c.Oa=P.Va.file.node,c.Pa=P.Va.file.stream,c.Ra=0,c.Na=null):40960===(c.mode&61440)?(c.Oa=P.Va.link.node,c.Pa=P.Va.link.stream):8192===(c.mode&61440)&&(c.Oa=P.Va.nb.node,c.Pa=P.Va.nb.stream);c.timestamp=Date.now();a&&(a.Na[b]=c);return c},Yd:function(a){if(a.Na&&
a.Na.subarray){for(var b=[],c=0;c<a.Ra;++c)b.push(a.Na[c]);return b}return a.Na},Zd:function(a){return a.Na?a.Na.subarray?a.Na.subarray(0,a.Ra):new Uint8Array(a.Na):new Uint8Array},ob:function(a,b){var c=a.Na?a.Na.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.Na,a.Na=new Uint8Array(b),0<a.Ra&&a.Na.set(c.subarray(0,a.Ra),0))},Fb:function(a,b){if(a.Ra!=b)if(0==b)a.Na=null,a.Ra=0;else{if(!a.Na||a.Na.subarray){var c=a.Na;a.Na=new Uint8Array(new ArrayBuffer(b));c&&
a.Na.set(c.subarray(0,Math.min(b,a.Ra)))}else if(a.Na||(a.Na=[]),a.Na.length>b)a.Na.length=b;else for(;a.Na.length<b;)a.Na.push(0);a.Ra=b}},Oa:{Wa:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.Ra:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Ya=4096;b.blocks=Math.ceil(b.size/
b.Ya);return b},Ua:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&P.Fb(a,b.size)},lookup:function(){throw jb[2];},bb:function(a,b,c,e){return P.createNode(a,b,c,e)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var e=kb(b,c)}catch(g){}if(e)for(var f in e.Na)throw new O(39);}delete a.parent.Na[a.name];a.name=c;b.Na[c]=a;a.parent=b},unlink:function(a,b){delete a.Na[b]},rmdir:function(a,b){var c=kb(a,b),e;for(e in c.Na)throw new O(39);
delete a.Na[b]},readdir:function(a){var b=[".",".."],c;for(c in a.Na)a.Na.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=P.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new O(22);return a.link}},Pa:{read:function(a,b,c,e,f){var g=a.node.Na;if(f>=a.node.Ra)return 0;a=Math.min(a.node.Ra-f,e);assert(0<=a);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(e=0;e<a;e++)b[c+e]=g[f+e];return a},write:function(a,b,c,e,f,g){if(!e)return 0;
a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Na||a.Na.subarray)){if(g)return assert(0===f,"canOwn must imply no weird position inside the file"),a.Na=b.subarray(c,c+e),a.Ra=e;if(0===a.Ra&&0===f)return a.Na=new Uint8Array(b.subarray(c,c+e)),a.Ra=e;if(f+e<=a.Ra)return a.Na.set(b.subarray(c,c+e),f),e}P.ob(a,f+e);if(a.Na.subarray&&b.subarray)a.Na.set(b.subarray(c,c+e),f);else for(g=0;g<e;g++)a.Na[f+g]=b[c+g];a.Ra=Math.max(a.Ra,f+e);return e},Xa:function(a,b,c){1===c?b+=a.position:2===c&&32768===
(a.node.mode&61440)&&(b+=a.node.Ra);if(0>b)throw new O(22);return b},lb:function(a,b,c){P.ob(a.node,b+c);a.node.Ra=Math.max(a.node.Ra,b+c)},ub:function(a,b,c,e,f,g,n){if(32768!==(a.node.mode&61440))throw new O(19);c=a.node.Na;if(n&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<f||f+e<a.node.Ra)c.subarray?c=c.subarray(f,f+e):c=Array.prototype.slice.call(c,f,f+e);a=!0;e=Ua(e);if(!e)throw new O(12);b.set(c,e)}else a=!1,e=c.byteOffset;return{$d:e,Xd:a}},wb:function(a,b,c,e,f){if(32768!==(a.node.mode&61440))throw new O(19);
if(f&2)return 0;P.Pa.write(a,b,0,e,c,!1);return 0}}},Q={eb:!1,Hb:function(){Q.eb=!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);Q.pb={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},mb:function(a){return Buffer.$a?Buffer.from(a):new Buffer(a)},Sa:function(a){assert(q);return Q.createNode(null,"/",Q.sb(a.ib.root),0)},createNode:function(a,b,c){if(16384!==(c&61440)&&32768!==(c&61440)&&40960!==(c&61440))throw new O(22);
a=ib(a,b,c);a.Oa=Q.Oa;a.Pa=Q.Pa;return a},sb:function(a){try{var b=fs.lstatSync(a);Q.eb&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;throw new O(-c.Qa);}return b.mode},Ta:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.Sa.ib.root);b.reverse();return $a.apply(null,b)},Ab:function(a){a&=-2656257;var b=0,c;for(c in Q.pb)a&c&&(b|=Q.pb[c],a^=c);if(a)throw new O(22);return b},Oa:{Wa:function(a){a=Q.Ta(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new O(-c.Qa);
}Q.eb&&!b.Ya&&(b.Ya=4096);Q.eb&&!b.blocks&&(b.blocks=(b.size+b.Ya-1)/b.Ya|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,Ya:b.Ya,blocks:b.blocks}},Ua:function(a,b){var c=Q.Ta(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(e){if(!e.code)throw e;throw new O(-e.Qa);}},lookup:function(a,b){var c=N(Q.Ta(a),b);c=Q.sb(c);return Q.createNode(a,b,c)},
bb:function(a,b,c,e){a=Q.createNode(a,b,c,e);b=Q.Ta(a);try{16384===(a.mode&61440)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(f){if(!f.code)throw f;throw new O(-f.Qa);}return a},rename:function(a,b,c){a=Q.Ta(a);b=N(Q.Ta(b),c);try{fs.renameSync(a,b)}catch(e){if(!e.code)throw e;throw new O(-e.Qa);}},unlink:function(a,b){a=N(Q.Ta(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new O(-c.Qa);}},rmdir:function(a,b){a=N(Q.Ta(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;
throw new O(-c.Qa);}},readdir:function(a){a=Q.Ta(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new O(-b.Qa);}},symlink:function(a,b,c){a=N(Q.Ta(a),b);try{fs.symlinkSync(c,a)}catch(e){if(!e.code)throw e;throw new O(-e.Qa);}},readlink:function(a){var b=Q.Ta(a);try{return b=fs.readlinkSync(b),b=lb.relative(lb.resolve(a.Sa.ib.root),b)}catch(c){if(!c.code)throw c;throw new O(-c.Qa);}}},Pa:{open:function(a){var b=Q.Ta(a.node);try{32768===(a.node.mode&61440)&&(a.cb=fs.openSync(b,Q.Ab(a.flags)))}catch(c){if(!c.code)throw c;
throw new O(-c.Qa);}},close:function(a){try{32768===(a.node.mode&61440)&&a.cb&&fs.closeSync(a.cb)}catch(b){if(!b.code)throw b;throw new O(-b.Qa);}},read:function(a,b,c,e,f){if(0===e)return 0;try{return fs.readSync(a.cb,Q.mb(b.buffer),c,e,f)}catch(g){throw new O(-g.Qa);}},write:function(a,b,c,e,f){try{return fs.writeSync(a.cb,Q.mb(b.buffer),c,e,f)}catch(g){throw new O(-g.Qa);}},Xa:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.cb).size}catch(e){throw new O(-e.Qa);
}if(0>b)throw new O(22);return b}}},mb={0:"Success",1:"Not super-user",2:"No such file or directory",3:"No such process",4:"Interrupted system call",5:"I/O error",6:"No such device or address",7:"Arg list too long",8:"Exec format error",9:"Bad file number",10:"No children",11:"No more processes",12:"Not enough core",13:"Permission denied",14:"Bad address",15:"Block device required",16:"Mount device busy",17:"File exists",18:"Cross-device link",19:"No such device",20:"Not a directory",21:"Is a directory",
22:"Invalid argument",23:"Too many open files in system",24:"Too many open files",25:"Not a typewriter",26:"Text file busy",27:"File too large",28:"No space left on device",29:"Illegal seek",30:"Read only file system",31:"Too many links",32:"Broken pipe",33:"Math arg out of domain of func",34:"Math result not representable",35:"File locking deadlock error",36:"File or path name too long",37:"No record locks available",38:"Function not implemented",39:"Directory not empty",40:"Too many symbolic links",
42:"No message of desired type",43:"Identifier removed",44:"Channel number out of range",45:"Level 2 not synchronized",46:"Level 3 halted",47:"Level 3 reset",48:"Link number out of range",49:"Protocol driver not attached",50:"No CSI structure available",51:"Level 2 halted",52:"Invalid exchange",53:"Invalid request descriptor",54:"Exchange full",55:"No anode",56:"Invalid request code",57:"Invalid slot",59:"Bad font file fmt",60:"Device not a stream",61:"No data (for no delay io)",62:"Timer expired",
63:"Out of streams resources",64:"Machine is not on the network",65:"Package not installed",66:"The object is remote",67:"The link has been severed",68:"Advertise error",69:"Srmount error",70:"Communication error on send",71:"Protocol error",72:"Multihop attempted",73:"Cross mount point (not really error)",74:"Trying to read unreadable message",75:"Value too large for defined data type",76:"Given log. name not unique",77:"f.d. invalid for this operation",78:"Remote address changed",79:"Can   access a needed shared lib",
80:"Accessing a corrupted shared lib",81:".lib section in a.out corrupted",82:"Attempting to link in too many libs",83:"Attempting to exec a shared library",84:"Illegal byte sequence",86:"Streams pipe error",87:"Too many users",88:"Socket operation on non-socket",89:"Destination address required",90:"Message too long",91:"Protocol wrong type for socket",92:"Protocol not available",93:"Unknown protocol",94:"Socket type not supported",95:"Not supported",96:"Protocol family not supported",97:"Address family not supported by protocol family",
98:"Address already in use",99:"Address not available",100:"Network interface is not configured",101:"Network is unreachable",102:"Connection reset by network",103:"Connection aborted",104:"Connection reset by peer",105:"No buffer space available",106:"Socket is already connected",107:"Socket is not connected",108:"Can't send after socket shutdown",109:"Too many references",110:"Connection timed out",111:"Connection refused",112:"Host is down",113:"Host is unreachable",114:"Socket already connected",
115:"Connection already in progress",116:"Stale file handle",122:"Quota exceeded",123:"No medium (in tape drive)",125:"Operation canceled",130:"Previous owner died",131:"State not recoverable"},R={xd:1,Xc:2,Kd:3,uc:4,vc:5,ud:6,Jb:7,Yc:8,xb:9,$b:10,Pb:11,Ud:11,bd:12,Kb:13,nc:14,md:15,Yb:16,mc:17,Vd:18,Wc:19,od:20,xc:21,yb:22,Rc:23,Jc:24,Za:25,Rd:26,oc:27,hd:28,Jd:29,Gd:30,Kc:31,zd:32,jc:33,Dd:34,cd:42,rc:43,ac:44,zc:45,Ac:46,Bc:47,Hc:48,Sd:49,Uc:50,yc:51,fc:35,Zc:37,Rb:52,Ub:53,Wd:54,Sc:55,Vb:56,Wb:57,
hc:35,Xb:59,kd:60,Vc:61,Od:62,jd:63,dd:64,ed:65,Fd:66,$c:67,Nb:68,Ld:69,bc:70,Ad:71,Mc:72,kc:73,Tb:74,td:76,Sb:77,Ed:78,Cc:79,Dc:80,Gc:81,Fc:82,Ec:83,ld:38,pd:39,Nc:36,Ic:40,vd:95,yd:96,ec:104,Tc:105,Ob:97,Cd:91,rd:88,gd:92,Hd:108,dc:111,Lb:98,cc:103,Qc:101,Oc:100,Pd:110,pc:112,qc:113,tc:115,Qb:114,ic:89,Lc:90,Bd:93,Id:94,Mb:99,Pc:102,wc:106,nd:107,Qd:109,Td:87,lc:122,Md:116,sd:95,ad:123,sc:84,zb:75,Zb:125,qd:131,wd:130,Nd:86},nb=null,ob={},pb=[],qb=1,rb=null,sb=!0,tb={},O=null,jb={};
function S(a,b){a=ab("/",a);b=b||{};if(!a)return{path:"",node:null};var c={rb:!0,kb:0},e;for(e in c)void 0===b[e]&&(b[e]=c[e]);if(8<b.kb)throw new O(40);a=Va(a.split("/").filter(function(a){return!!a}),!1);var f=nb;c="/";for(e=0;e<a.length;e++){var g=e===a.length-1;if(g&&b.parent)break;f=kb(f,a[e]);c=N(c,a[e]);f.fb&&(!g||g&&b.rb)&&(f=f.fb.root);if(!g||b.qb)for(g=0;40960===(f.mode&61440);)if(f=vb(c),c=ab(Ya(c),f),f=S(c,{kb:b.kb}).node,40<g++)throw new O(40);}return{path:c,node:f}}
function wb(a){for(var b;;){if(a===a.parent)return a=a.Sa.vb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function xb(a,b){for(var c=0,e=0;e<b.length;e++)c=(c<<5)-c+b.charCodeAt(e)|0;return(a+c>>>0)%rb.length}function yb(a){var b=xb(a.parent.id,a.name);a.Eb=rb[b];rb[b]=a}function kb(a,b){var c;if(c=(c=zb(a,"x"))?c:a.Oa.lookup?0:13)throw new O(c,a);for(c=rb[xb(a.id,b)];c;c=c.Eb){var e=c.name;if(c.parent.id===a.id&&e===b)return c}return a.Oa.lookup(a,b)}
function ib(a,b,c,e){Ab||(Ab=function(a,b,c,e){a||(a=this);this.parent=a;this.Sa=a.Sa;this.fb=null;this.id=qb++;this.name=b;this.mode=c;this.Oa={};this.Pa={};this.rdev=e},Ab.prototype={},Object.defineProperties(Ab.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}}));a=new Ab(a,b,c,e);yb(a);return a}
var Bb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Cb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function zb(a,b){if(sb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 13}else return 13;return 0}function Db(a,b){try{return kb(a,b),17}catch(c){}return zb(a,"wx")}
function Eb(){var a=4096;for(var b=0;b<=a;b++)if(!pb[b])return b;throw new O(24);}function Fb(a){Gb||(Gb=function(){},Gb.prototype={},Object.defineProperties(Gb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var b=new Gb,c;for(c in a)b[c]=a[c];a=b;b=Eb();a.fd=b;return pb[b]=a}var hb={open:function(a){a.Pa=ob[a.node.rdev].Pa;a.Pa.open&&a.Pa.open(a)},Xa:function(){throw new O(29);}};function db(a,b){ob[a]={Pa:b}}
function Hb(a,b){var c="/"===b,e=!b;if(c&&nb)throw new O(16);if(!c&&!e){var f=S(b,{rb:!1});b=f.path;f=f.node;if(f.fb)throw new O(16);if(16384!==(f.mode&61440))throw new O(20);}b={type:a,ib:{},vb:b,Db:[]};a=a.Sa(b);a.Sa=b;b.root=a;c?nb=a:f&&(f.fb=b,f.Sa&&f.Sa.Db.push(b))}function Ib(a,b,c){var e=S(a,{parent:!0}).node;a=Za(a);if(!a||"."===a||".."===a)throw new O(22);var f=Db(e,a);if(f)throw new O(f);if(!e.Oa.bb)throw new O(1);return e.Oa.bb(e,a,b,c)}function T(a){Ib(a,16895,0)}
function Jb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Ib(a,b|8192,c)}function Kb(a,b){if(!ab(a))throw new O(2);var c=S(b,{parent:!0}).node;if(!c)throw new O(2);b=Za(b);var e=Db(c,b);if(e)throw new O(e);if(!c.Oa.symlink)throw new O(1);c.Oa.symlink(c,b,a)}function vb(a){a=S(a).node;if(!a)throw new O(2);if(!a.Oa.readlink)throw new O(22);return ab(wb(a.parent),a.Oa.readlink(a))}
function Lb(a,b,c){if(""===a)throw new O(2);if("string"===typeof b){var e=Bb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=Xa(a);try{f=S(a,{qb:!(b&131072)}).node}catch(n){}}e=!1;if(b&64)if(f){if(b&128)throw new O(17);}else f=Ib(a,c,0),e=!0;if(!f)throw new O(2);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new O(20);if(!e&&(c=f?40960===(f.mode&61440)?40:
16384===(f.mode&61440)&&("r"!==Cb(b)||b&512)?21:zb(f,Cb(b)):2))throw new O(c);if(b&512){c=f;var g;"string"===typeof c?g=S(c,{qb:!0}).node:g=c;if(!g.Oa.Ua)throw new O(1);if(16384===(g.mode&61440))throw new O(21);if(32768!==(g.mode&61440))throw new O(22);if(c=zb(g,"w"))throw new O(c);g.Oa.Ua(g,{size:0,timestamp:Date.now()})}b&=-641;f=Fb({node:f,path:wb(f),flags:b,seekable:!0,position:0,Pa:f.Pa,Ib:[],error:!1});f.Pa.open&&f.Pa.open(f);!h.logReadFiles||b&1||(Mb||(Mb={}),a in Mb||(Mb[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{tb.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),tb.onOpenFile(a,g))}catch(n){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+n.message)}return f}function Nb(a,b,c){if(null===a.fd)throw new O(9);if(!a.seekable||!a.Pa.Xa)throw new O(29);if(0!=c&&1!=c&&2!=c)throw new O(22);a.position=a.Pa.Xa(a,b,c);a.Ib=[]}
function Ob(){O||(O=function(a,b){this.node=b;this.Gb=function(a){this.Qa=a;for(var b in R)if(R[b]===a){this.code=b;break}};this.Gb(a);this.message=mb[a];this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0});this.stack&&(this.stack=xa(this.stack))},O.prototype=Error(),O.prototype.constructor=O,[2].forEach(function(a){jb[a]=new O(a);jb[a].stack="<generic error, no stack>"}))}var Pb;function Qb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Rb(a,b,c){a=N("/dev",a);var e=Qb(!!b,!!c);Sb||(Sb=64);var f=Sb++<<8|0;db(f,{open:function(a){a.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(a,c,e,f){for(var g=0,n=0;n<f;n++){try{var r=b()}catch(Ea){throw new O(5);}if(void 0===r&&0===g)throw new O(11);if(null===r||void 0===r)break;g++;c[e+n]=r}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,e,f){for(var g=0;g<f;g++)try{c(b[e+g])}catch(W){throw new O(5);}f&&(a.node.timestamp=Date.now());return g}});
Jb(a,e,f)}var Sb,U={},Ab,Gb,Mb,X=0;function Y(){X+=4;return x[X-4>>2]}function Tb(){var a=pb[Y()];if(!a)throw new O(R.xb);return a}function ma(){return B.length}
function Ub(a){u("Cannot enlarge memory arrays to size "+a+" bytes (OOM). Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+B.length+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}
function Vb(a){if(0===a)return 0;a=C(a);if(!M.hasOwnProperty(a))return 0;Vb.$a&&Wb(Vb.$a);a=M[a];var b=wa(a)+1,c=Ua(b);c&&ua(a,B,c,b);Vb.$a=c;return Vb.$a}Ob();rb=Array(4096);Hb(P,"/");T("/tmp");T("/home");T("/home/web_user");
(function(){T("/dev");db(259,{read:function(){return 0},write:function(a,b,c,n){return n}});Jb("/dev/null",259);cb(1280,fb);cb(1536,gb);Jb("/dev/tty",1280);Jb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(q)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(e){}b||(b=function(){u("no cryptographic support found for random_device. consider polyfilling it if you want to use something insecure like Math.random(), e.g. put this in a --pre-js: var crypto = { getRandomValues: function(array) { for (var i = 0; i < array.length; i++) array[i] = (Math.random()*256)|0 } };")});
Rb("random",b);Rb("urandom",b);T("/dev/shm");T("/dev/shm/tmp")})();T("/proc");T("/proc/self");T("/proc/self/fd");Hb({Sa:function(){var a=ib("/proc/self","fd",16895,73);a.Oa={lookup:function(a,c){var b=pb[+c];if(!b)throw new O(9);a={parent:null,Sa:{vb:"fake"},Oa:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");if(q){var fs={},lb=require("path");Q.Hb()}
var Z=h.asm({},{y:function(){return 0},b:function(a){u("Stack overflow! Attempted to allocate "+a+" bytes on the stack, but stack has only "+(5255776-ha()+a)+" bytes available!")},W:function(a){v("Invalid function pointer called with signature 'ii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");
v("Build with ASSERTIONS=2 for more info.");u(a)},Q:function(a){v("Invalid function pointer called with signature 'iii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");v("Build with ASSERTIONS=2 for more info.");u(a)},N:function(a){v("Invalid function pointer called with signature 'iiii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");
v("Build with ASSERTIONS=2 for more info.");u(a)},F:function(a){v("Invalid function pointer called with signature 'iiiii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");v("Build with ASSERTIONS=2 for more info.");u(a)},w:function(a){v("Invalid function pointer called with signature 'iiiiii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");
v("Build with ASSERTIONS=2 for more info.");u(a)},v:function(a){v("Invalid function pointer called with signature 'iiiiiiiiiii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");v("Build with ASSERTIONS=2 for more info.");u(a)},u:function(a){v("Invalid function pointer called with signature 'jiji'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");
v("Build with ASSERTIONS=2 for more info.");u(a)},t:function(a){v("Invalid function pointer called with signature 'vi'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");v("Build with ASSERTIONS=2 for more info.");u(a)},s:function(a){v("Invalid function pointer called with signature 'vii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");
v("Build with ASSERTIONS=2 for more info.");u(a)},V:function(a){v("Invalid function pointer called with signature 'viii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");v("Build with ASSERTIONS=2 for more info.");u(a)},U:function(a){v("Invalid function pointer called with signature 'viiii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");
v("Build with ASSERTIONS=2 for more info.");u(a)},T:function(a){v("Invalid function pointer called with signature 'viiiii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");v("Build with ASSERTIONS=2 for more info.");u(a)},S:function(a){v("Invalid function pointer called with signature 'viiiiii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");
v("Build with ASSERTIONS=2 for more info.");u(a)},R:function(a){v("Invalid function pointer called with signature 'viiiiiiiii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");v("Build with ASSERTIONS=2 for more info.");u(a)},o:function(a,b){return y[a](b)},
n:function(a,b,c){return y[a](b,c)},m:function(a,b,c,e){return y[a](b,c,e)},l:function(a,b,c,e,f){return y[a](b,c,e,f)},k:function(a,b,c,e,f,g){return y[a](b,c,e,f,g)},j:function(a,b,c,e,f,g,n,r,z,V,W){return y[a](b,c,e,f,g,n,r,z,V,W)},x:function(a,b,c,e){return y[a](b,c,e)},i:function(a,b){y[a](b)},h:function(a,b,c){y[a](b,c)},g:function(a,b,c,e){y[a](b,c,e)},f:function(a,b,c,e,f){y[a](b,c,e,f)},e:function(a,b,c,e,f,g){y[a](b,c,e,f,g)},d:function(a,b,c,e,f,g,n){y[a](b,c,e,f,g,n)},c:function(a,b,
c,e,f,g,n,r,z,V){y[a](b,c,e,f,g,n,r,z,V)},P:function(a,b,c,e){u("Assertion failed: "+C(a)+", at: "+[b?C(b):"unknown filename",c,e?C(e):"unknown function"])},O:Ta,M:function(){},r:function(a){h.___errno_location?x[h.___errno_location()>>2]=a:v("failed to set errno from JS");return a},L:function(a,b){X=b;try{var c=Tb(),e=Y(),f=Y(),g=Y(),n=Y();if(!(-1==e&&0>f||0==e&&0<=f))return-R.zb;Nb(c,f,n);aa=[c.position>>>0,(d=c.position,1<=+Ia(d)?0<d?(La(+Ka(d/4294967296),4294967295)|0)>>>0:~~+Ja((d-+(~~d>>>0))/
4294967296)>>>0:0)];x[g>>2]=aa[0];x[g+4>>2]=aa[1];c.hb&&0===f&&0===n&&(c.hb=null);return 0}catch(r){return"undefined"!==typeof U&&r instanceof O||u(r),-r.Qa}},q:function(a,b){X=b;try{var c=Tb(),e=Y();a:{var f=Y();for(b=a=0;b<f;b++){var g=c,n=x[e+8*b>>2],r=x[e+(8*b+4)>>2],z=void 0,V=B;if(0>r||0>z)throw new O(22);if(null===g.fd)throw new O(9);if(0===(g.flags&2097155))throw new O(9);if(16384===(g.node.mode&61440))throw new O(21);if(!g.Pa.write)throw new O(22);g.flags&1024&&Nb(g,0,2);var W="undefined"!==
typeof z;if(!W)z=g.position;else if(!g.seekable)throw new O(29);var Wa=g.Pa.write(g,V,n,r,z,void 0);W||(g.position+=Wa);try{if(g.path&&tb.onWriteToFile)tb.onWriteToFile(g.path)}catch(ia){console.log("FS.trackingDelegate['onWriteToFile']('"+g.path+"') threw an exception: "+ia.message)}var Ea=Wa;if(0>Ea){var ub=-1;break a}a+=Ea}ub=a}return ub}catch(ia){return"undefined"!==typeof U&&ia instanceof O||u(ia),-ia.Qa}},K:function(a,b){X=b;return 42},J:function(a,b){X=b;try{var c=Tb(),e=Y(),f=Y();a=B;if(0>
f||0>g)throw new O(22);if(null===c.fd)throw new O(9);if(1===(c.flags&2097155))throw new O(9);if(16384===(c.node.mode&61440))throw new O(21);if(!c.Pa.read)throw new O(22);b="undefined"!==typeof g;if(!b)var g=c.position;else if(!c.seekable)throw new O(29);var n=c.Pa.read(c,a,e,f,g);b||(c.position+=n);return n}catch(r){return"undefined"!==typeof U&&r instanceof O||u(r),-r.Qa}},I:function(a,b){X=b;try{var c=C(Y()),e=Y(),f=Y();return Lb(c,e,f).fd}catch(g){return"undefined"!==typeof U&&g instanceof O||
u(g),-g.Qa}},H:function(a,b){X=b;try{var c=Tb(),e=Y();switch(e){case 21509:case 21505:return c.tty?0:-R.Za;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-R.Za;case 21519:if(!c.tty)return-R.Za;var f=Y();return x[f>>2]=0;case 21520:return c.tty?-R.yb:-R.Za;case 21531:a=f=Y();if(!c.Pa.Cb)throw new O(25);return c.Pa.Cb(c,e,a);case 21523:return c.tty?0:-R.Za;case 21524:return c.tty?0:-R.Za;default:u("bad ioctl syscall "+e)}}catch(g){return"undefined"!==typeof U&&g instanceof
O||u(g),-g.Qa}},p:function(a,b){X=b;try{var c=Tb();if(null===c.fd)throw new O(9);c.hb&&(c.hb=null);try{c.Pa.close&&c.Pa.close(c)}catch(e){throw e;}finally{pb[c.fd]=null}c.fd=null;return 0}catch(e){return"undefined"!==typeof U&&e instanceof O||u(e),-e.Qa}},G:function(){},E:ma,D:function(a,b,c){A.set(A.subarray(b,b+c),a)},C:function(a){Ub(a)},B:Vb,A:function(a){var b=Date.now();x[a>>2]=b/1E3|0;x[a+4>>2]=b%1E3*1E3|0;return 0},z:Ub,a:w},buffer),Xb=Z.X;
Z.X=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Xb.apply(null,arguments)};var Yb=Z.Y;Z.Y=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Yb.apply(null,arguments)};var Zb=Z.Z;
Z.Z=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Zb.apply(null,arguments)};var $b=Z._;Z._=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return $b.apply(null,arguments)};var ac=Z.$;
Z.$=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return ac.apply(null,arguments)};var bc=Z.aa;Z.aa=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return bc.apply(null,arguments)};var cc=Z.ba;
Z.ba=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return cc.apply(null,arguments)};var dc=Z.ca;Z.ca=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return dc.apply(null,arguments)};var ec=Z.da;
Z.da=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return ec.apply(null,arguments)};var fc=Z.ea;Z.ea=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return fc.apply(null,arguments)};var hc=Z.fa;
Z.fa=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return hc.apply(null,arguments)};var ic=Z.ga;Z.ga=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return ic.apply(null,arguments)};var jc=Z.ha;
Z.ha=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return jc.apply(null,arguments)};var kc=Z.ia;Z.ia=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return kc.apply(null,arguments)};var lc=Z.ja;
Z.ja=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return lc.apply(null,arguments)};var mc=Z.ka;Z.ka=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return mc.apply(null,arguments)};var nc=Z.la;
Z.la=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return nc.apply(null,arguments)};var oc=Z.ma;Z.ma=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return oc.apply(null,arguments)};var pc=Z.na;
Z.na=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return pc.apply(null,arguments)};var qc=Z.oa;Z.oa=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return qc.apply(null,arguments)};var rc=Z.pa;
Z.pa=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return rc.apply(null,arguments)};var sc=Z.qa;Z.qa=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return sc.apply(null,arguments)};var tc=Z.ra;
Z.ra=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return tc.apply(null,arguments)};var uc=Z.sa;Z.sa=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return uc.apply(null,arguments)};var vc=Z.ta;
Z.ta=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return vc.apply(null,arguments)};var wc=Z.ua;Z.ua=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return wc.apply(null,arguments)};var xc=Z.va;
Z.va=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return xc.apply(null,arguments)};var yc=Z.wa;Z.wa=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return yc.apply(null,arguments)};var zc=Z.xa;
Z.xa=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return zc.apply(null,arguments)};var Ac=Z.ya;Z.ya=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Ac.apply(null,arguments)};var Bc=Z.za;
Z.za=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Bc.apply(null,arguments)};var Cc=Z.Aa;Z.Aa=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Cc.apply(null,arguments)};var Dc=Z.Ba;
Z.Ba=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Dc.apply(null,arguments)};var Ec=Z.Ca;Z.Ca=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Ec.apply(null,arguments)};var Fc=Z.Da;
Z.Da=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Fc.apply(null,arguments)};var Gc=Z.Ea;Z.Ea=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Gc.apply(null,arguments)};var Hc=Z.Fa;
Z.Fa=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Hc.apply(null,arguments)};var Ic=Z.Ga;Z.Ga=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Ic.apply(null,arguments)};var Jc=Z.Ha;
Z.Ha=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Jc.apply(null,arguments)};var Kc=Z.Ja;Z.Ja=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Kc.apply(null,arguments)};var Lc=Z.Ka;
Z.Ka=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Lc.apply(null,arguments)};var Mc=Z.La;Z.La=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Mc.apply(null,arguments)};var Nc=Z.Ma;
Z.Ma=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Nc.apply(null,arguments)};h.asm=Z;h._XML_ErrorString=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.X.apply(null,arguments)};
h._XML_ExpatVersion=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.Y.apply(null,arguments)};
h._XML_FreeContentModel=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.Z.apply(null,arguments)};
h._XML_GetCurrentColumnNumber=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm._.apply(null,arguments)};
h._XML_GetCurrentLineNumber=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.$.apply(null,arguments)};
h._XML_GetErrorCode=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.aa.apply(null,arguments)};h._XML_Parse=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.ba.apply(null,arguments)};
h._XML_ParserCreate=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.ca.apply(null,arguments)};
h._XML_ParserCreateNS=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.da.apply(null,arguments)};
h._XML_ParserFree=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.ea.apply(null,arguments)};h._XML_ParserReset=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.fa.apply(null,arguments)};
h._XML_SetAttlistDeclHandler=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.ga.apply(null,arguments)};
h._XML_SetCharacterDataHandler=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.ha.apply(null,arguments)};
h._XML_SetCommentHandler=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.ia.apply(null,arguments)};
h._XML_SetDefaultHandler=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.ja.apply(null,arguments)};
h._XML_SetElementDeclHandler=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.ka.apply(null,arguments)};
h._XML_SetEndCdataSectionHandler=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.la.apply(null,arguments)};
h._XML_SetEndDoctypeDeclHandler=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.ma.apply(null,arguments)};
h._XML_SetEndElementHandler=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.na.apply(null,arguments)};
h._XML_SetEndNamespaceDeclHandler=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.oa.apply(null,arguments)};
h._XML_SetEntityDeclHandler=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.pa.apply(null,arguments)};
h._XML_SetNotationDeclHandler=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.qa.apply(null,arguments)};
h._XML_SetParamEntityParsing=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.ra.apply(null,arguments)};
h._XML_SetProcessingInstructionHandler=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.sa.apply(null,arguments)};
h._XML_SetReturnNSTriplet=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.ta.apply(null,arguments)};
h._XML_SetStartCdataSectionHandler=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.ua.apply(null,arguments)};
h._XML_SetStartDoctypeDeclHandler=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.va.apply(null,arguments)};
h._XML_SetStartElementHandler=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.wa.apply(null,arguments)};
h._XML_SetStartNamespaceDeclHandler=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.xa.apply(null,arguments)};
h._XML_SetUserData=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.ya.apply(null,arguments)};
h._XML_SetXmlDeclHandler=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.za.apply(null,arguments)};
var Sa=h.___emscripten_environ_constructor=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.Aa.apply(null,arguments)};
h.___errno_location=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.Ba.apply(null,arguments)};h.__get_environ=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.Ca.apply(null,arguments)};
h._fflush=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.Da.apply(null,arguments)};
var Wb=h._free=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.Ea.apply(null,arguments)},Ua=h._malloc=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.Fa.apply(null,arguments)};
h._memmove=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.Ga.apply(null,arguments)};h._sbrk=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.Ha.apply(null,arguments)};
h.establishStackSpace=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.Ja.apply(null,arguments)};
var ka=h.stackAlloc=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.Ka.apply(null,arguments)},ja=h.stackRestore=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.La.apply(null,arguments)},
ha=h.stackSave=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.Ma.apply(null,arguments)};h.dynCall_vi=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return h.asm.Ia.apply(null,arguments)};
h.asm=Z;h.intArrayFromString||(h.intArrayFromString=function(){u("'intArrayFromString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.intArrayToString||(h.intArrayToString=function(){u("'intArrayToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.ccall||(h.ccall=function(){u("'ccall' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.cwrap=function(a,b,c){return function(){return ta(a,b,c,arguments)}};
h.setValue||(h.setValue=function(){u("'setValue' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.getValue||(h.getValue=function(){u("'getValue' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.allocate||(h.allocate=function(){u("'allocate' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.getMemory||(h.getMemory=function(){u("'getMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
h.AsciiToString||(h.AsciiToString=function(){u("'AsciiToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.stringToAscii||(h.stringToAscii=function(){u("'stringToAscii' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.UTF8ArrayToString||(h.UTF8ArrayToString=function(){u("'UTF8ArrayToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.UTF8ToString=C;h.stringToUTF8Array||(h.stringToUTF8Array=function(){u("'stringToUTF8Array' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
h.stringToUTF8||(h.stringToUTF8=function(){u("'stringToUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.lengthBytesUTF8||(h.lengthBytesUTF8=function(){u("'lengthBytesUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.UTF16ToString||(h.UTF16ToString=function(){u("'UTF16ToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.stringToUTF16||(h.stringToUTF16=function(){u("'stringToUTF16' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
h.lengthBytesUTF16||(h.lengthBytesUTF16=function(){u("'lengthBytesUTF16' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.UTF32ToString||(h.UTF32ToString=function(){u("'UTF32ToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.stringToUTF32||(h.stringToUTF32=function(){u("'stringToUTF32' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.lengthBytesUTF32||(h.lengthBytesUTF32=function(){u("'lengthBytesUTF32' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
h.allocateUTF8||(h.allocateUTF8=function(){u("'allocateUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.stackTrace||(h.stackTrace=function(){u("'stackTrace' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.addOnPreRun||(h.addOnPreRun=function(){u("'addOnPreRun' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.addOnInit||(h.addOnInit=function(){u("'addOnInit' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
h.addOnPreMain||(h.addOnPreMain=function(){u("'addOnPreMain' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.addOnExit||(h.addOnExit=function(){u("'addOnExit' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.addOnPostRun||(h.addOnPostRun=function(){u("'addOnPostRun' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.writeStringToMemory||(h.writeStringToMemory=function(){u("'writeStringToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
h.writeArrayToMemory||(h.writeArrayToMemory=function(){u("'writeArrayToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.writeAsciiToMemory||(h.writeAsciiToMemory=function(){u("'writeAsciiToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.addRunDependency||(h.addRunDependency=function(){u("'addRunDependency' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
h.removeRunDependency||(h.removeRunDependency=function(){u("'removeRunDependency' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});h.ENV||(h.ENV=function(){u("'ENV' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.FS||(h.FS=function(){u("'FS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
h.FS_createFolder||(h.FS_createFolder=function(){u("'FS_createFolder' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});h.FS_createPath||(h.FS_createPath=function(){u("'FS_createPath' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
h.FS_createDataFile||(h.FS_createDataFile=function(){u("'FS_createDataFile' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});h.FS_createPreloadedFile||(h.FS_createPreloadedFile=function(){u("'FS_createPreloadedFile' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
h.FS_createLazyFile||(h.FS_createLazyFile=function(){u("'FS_createLazyFile' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});h.FS_createLink||(h.FS_createLink=function(){u("'FS_createLink' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
h.FS_createDevice||(h.FS_createDevice=function(){u("'FS_createDevice' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});h.FS_unlink||(h.FS_unlink=function(){u("'FS_unlink' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});h.GL||(h.GL=function(){u("'GL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
h.dynamicAlloc||(h.dynamicAlloc=function(){u("'dynamicAlloc' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.warnOnce||(h.warnOnce=function(){u("'warnOnce' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.loadDynamicLibrary||(h.loadDynamicLibrary=function(){u("'loadDynamicLibrary' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.loadWebAssemblyModule||(h.loadWebAssemblyModule=function(){u("'loadWebAssemblyModule' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
h.getLEB||(h.getLEB=function(){u("'getLEB' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.getFunctionTables||(h.getFunctionTables=function(){u("'getFunctionTables' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.alignFunctionTables||(h.alignFunctionTables=function(){u("'alignFunctionTables' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.registerFunctions||(h.registerFunctions=function(){u("'registerFunctions' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
h.addFunction=function(a){for(var b=0;30>b;b++)if(!y[b])return y[b]=a,1+b;throw"Finished up all reserved function pointers. Use a higher value for RESERVED_FUNCTION_POINTERS.";};h.removeFunction=function(a){y[a-1]=null};h.getFuncWrapper||(h.getFuncWrapper=function(){u("'getFuncWrapper' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.prettyPrint||(h.prettyPrint=function(){u("'prettyPrint' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
h.makeBigInt||(h.makeBigInt=function(){u("'makeBigInt' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.dynCall||(h.dynCall=function(){u("'dynCall' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.getCompilerSetting||(h.getCompilerSetting=function(){u("'getCompilerSetting' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.stackSave||(h.stackSave=function(){u("'stackSave' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
h.stackRestore||(h.stackRestore=function(){u("'stackRestore' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.stackAlloc||(h.stackAlloc=function(){u("'stackAlloc' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.establishStackSpace||(h.establishStackSpace=function(){u("'establishStackSpace' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.print||(h.print=function(){u("'print' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
h.printErr||(h.printErr=function(){u("'printErr' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.getTempRet0||(h.getTempRet0=function(){u("'getTempRet0' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.setTempRet0||(h.setTempRet0=function(){u("'setTempRet0' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.Pointer_stringify||(h.Pointer_stringify=function(){u("'Pointer_stringify' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
h.writeStackCookie||(h.writeStackCookie=function(){u("'writeStackCookie' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.checkStackCookie||(h.checkStackCookie=function(){u("'checkStackCookie' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});h.abortStackOverflow||(h.abortStackOverflow=function(){u("'abortStackOverflow' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
h.ALLOC_NORMAL||Object.defineProperty(h,"ALLOC_NORMAL",{get:function(){u("'ALLOC_NORMAL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});h.ALLOC_STACK||Object.defineProperty(h,"ALLOC_STACK",{get:function(){u("'ALLOC_STACK' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});h.ALLOC_DYNAMIC||Object.defineProperty(h,"ALLOC_DYNAMIC",{get:function(){u("'ALLOC_DYNAMIC' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});
h.ALLOC_NONE||Object.defineProperty(h,"ALLOC_NONE",{get:function(){u("'ALLOC_NONE' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});h.then=function(a){if(h.calledRun)a(h);else{var b=h.onRuntimeInitialized;h.onRuntimeInitialized=function(){b&&b();a(h)}}return h};function ea(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ea.prototype=Error();ea.prototype.constructor=ea;J=function Oc(){h.calledRun||Pc();h.calledRun||(J=Oc)};
function Pc(){function a(){if(!h.calledRun&&(h.calledRun=!0,!ra)){Aa();if(!G){G=!0;if(!h.noFSInit&&!Pb){assert(!Pb,"FS.init was previously called. If you want to initialize later with custom parameters, remove any earlier calls (note that one is automatically added to the generated code)");Pb=!0;Ob();h.stdin=h.stdin;h.stdout=h.stdout;h.stderr=h.stderr;h.stdin?Rb("stdin",h.stdin):Kb("/dev/tty","/dev/stdin");h.stdout?Rb("stdout",null,h.stdout):Kb("/dev/tty","/dev/stdout");h.stderr?Rb("stderr",null,
h.stderr):Kb("/dev/tty1","/dev/stderr");var a=Lb("/dev/stdin","r"),c=Lb("/dev/stdout","w"),e=Lb("/dev/stderr","w");assert(0===a.fd,"invalid handle for stdin ("+a.fd+")");assert(1===c.fd,"invalid handle for stdout ("+c.fd+")");assert(2===e.fd,"invalid handle for stderr ("+e.fd+")")}Ba(Da)}Aa();sb=!1;Ba(Fa);if(h.onRuntimeInitialized)h.onRuntimeInitialized();assert(!h._main,'compiled without a main, but one is present. if you added it from JS, use Module["onRuntimeInitialized"]');Aa();if(h.postRun)for("function"==
typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;)a=h.postRun.shift(),Ga.unshift(a);Ba(Ga)}}if(!(0<H)){assert(!0);E[1313943]=34821223;E[1313942]=2310721022;if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ha();Ba(Ca);0<H||h.calledRun||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);a()},1)):a(),Aa())}}h.run=Pc;var Qc=[];
function u(a){if(h.onAbort)h.onAbort(a);void 0!==a?(fa(a),v(a),a=JSON.stringify(a)):a="";ra=!0;var b="abort("+a+") at "+ya();Qc&&Qc.forEach(function(c){b=c(b,a)});throw b;}h.abort=u;if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();h.noExitRuntime=!0;Pc();


  return Module
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = Module;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return Module; });
    else if (typeof exports === 'object')
      exports["Module"] = Module;
    