var e;e||(e=typeof Module !== 'undefined' ? Module : {});e.locateFile=function(a){return require?require("path").join(__dirname,a):a};var h={},l;for(l in e)e.hasOwnProperty(l)&&(h[l]=e[l]);e.arguments=[];e.thisProgram="./this.program";e.quit=function(a,b){throw b;};e.preRun=[];e.postRun=[];var m=!1,n=!1,q=!1,aa=!1;m="object"===typeof window;n="function"===typeof importScripts;q="object"===typeof process&&"function"===typeof require&&!m&&!n;aa=!m&&!q&&!n;var r="";
if(q){r=__dirname+"/";var ba,ca;e.read=function(a,b){ba||(ba=require("fs"));ca||(ca=require("path"));a=ca.normalize(a);a=ba.readFileSync(a);return b?a:a.toString()};e.readBinary=function(a){a=e.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(e.thisProgram=process.argv[1].replace(/\\/g,"/"));e.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=e);process.on("uncaughtException",function(a){if(!(a instanceof da))throw a;});process.on("unhandledRejection",
t);e.quit=function(a){process.exit(a)};e.inspect=function(){return"[Emscripten Module object]"}}else if(aa)"undefined"!=typeof read&&(e.read=function(a){return read(a)}),e.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?e.arguments=scriptArgs:"undefined"!=typeof arguments&&(e.arguments=arguments),"function"===typeof quit&&(e.quit=function(a){quit(a)});else if(m||n)n?
r=self.location.href:document.currentScript&&(r=document.currentScript.src),r=0!==r.indexOf("blob:")?r.substr(0,r.lastIndexOf("/")+1):"",e.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},n&&(e.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),e.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==
d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},e.setWindowTitle=function(a){document.title=a};var ea=e.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),v=e.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||ea);for(l in h)h.hasOwnProperty(l)&&(e[l]=h[l]);h=void 0;function fa(a){var b=w[ha>>2];a=b+a+15&-16;if(a<=y)w[ha>>2]=a;else return 0;return b}
var ia={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},z=Array(30),ja=!1;function assert(a,b){a||t("Assertion failed: "+b)}function ka(a){var b=e["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
var pa={stackSave:function(){la()},stackRestore:function(){ma()},arrayToC:function(a){var b=na(a.length);A.set(a,b);return b},stringToC:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var c=(a.length<<2)+1;b=na(c);oa(a,C,b,c)}return b}},qa={string:pa.stringToC,array:pa.arrayToC};
function ra(a,b){if(0===b||!a)return"";for(var c=0,d,f=0;;){d=C[a+f>>0];c|=d;if(0==d&&!b)break;f++;if(b&&f==b)break}b||(b=f);d="";if(128>c){for(;0<b;)c=String.fromCharCode.apply(String,C.subarray(a,a+Math.min(b,1024))),d=d?d+c:c,a+=1024,b-=1024;return d}return D(C,a)}var sa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function D(a,b){for(var c=b;a[c];)++c;if(16<c-b&&a.subarray&&sa)return sa.decode(a.subarray(b,c));for(c="";;){var d=a[b++];if(!d)return c;if(d&128){var f=a[b++]&63;if(192==(d&224))c+=String.fromCharCode((d&31)<<6|f);else{var g=a[b++]&63;d=224==(d&240)?(d&15)<<12|f<<6|g:(d&7)<<18|f<<12|g<<6|a[b++]&63;65536>d?c+=String.fromCharCode(d):(d-=65536,c+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else c+=String.fromCharCode(d)}}
function oa(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var p=a.charCodeAt(++g);k=65536+((k&1023)<<10)|p&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-f}
function ta(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:2097151>=d?b+4:67108863>=d?b+5:b+6}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");var buffer,A,C,w;
function ua(){e.HEAP8=A=new Int8Array(buffer);e.HEAP16=new Int16Array(buffer);e.HEAP32=w=new Int32Array(buffer);e.HEAPU8=C=new Uint8Array(buffer);e.HEAPU16=new Uint16Array(buffer);e.HEAPU32=new Uint32Array(buffer);e.HEAPF32=new Float32Array(buffer);e.HEAPF64=new Float64Array(buffer)}var va=1024,ha=13376;
function wa(){t("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+y+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var y=e.TOTAL_MEMORY||16777216;5242880>y&&v("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+y+"! (TOTAL_STACK=5242880)");
e.buffer?buffer=e.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(e.wasmMemory=new WebAssembly.Memory({initial:y/65536,maximum:y/65536}),buffer=e.wasmMemory.buffer):buffer=new ArrayBuffer(y),e.buffer=buffer);ua();w[ha>>2]=5256512;function xa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.ib;"number"===typeof c?void 0===b.Ha?e.dynCall_v(c):e.dynCall_vi(c,b.Ha):c(void 0===b.Ha?null:b.Ha)}}}var ya=[],za=[],Aa=[],Ba=[],Ca=[],Da=!1;
function Ea(){var a=e.preRun.shift();ya.unshift(a)}var E=0,Ga=null,F=null;e.preloadedImages={};e.preloadedAudios={};function Ha(){var a=G;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var G="expat.wasm";if(!Ha()){var Ia=G;G=e.locateFile?e.locateFile(Ia,r):r+Ia}
function Ja(){try{if(e.wasmBinary)return new Uint8Array(e.wasmBinary);if(e.readBinary)return e.readBinary(G);throw"both async and sync fetching of the wasm failed";}catch(a){t(a)}}function Ka(){return e.wasmBinary||!m&&!n||"function"!==typeof fetch?new Promise(function(a){a(Ja())}):fetch(G,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+G+"'";return a.arrayBuffer()}).catch(function(){return Ja()})}
function La(a){function b(a){a=a.exports;if(a.memory){var b=a.memory,c=e.buffer;b.byteLength<c.byteLength&&v("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");c=new Int8Array(c);(new Int8Array(b)).set(c);e.buffer=buffer=b;ua()}e.asm=a;E--;e.monitorRunDependencies&&e.monitorRunDependencies(E);0==E&&(null!==Ga&&(clearInterval(Ga),Ga=null),F&&(a=F,F=null,a()))}function c(a){b(a.instance)}function d(a){Ka().then(function(a){return WebAssembly.instantiate(a,
f)}).then(a,function(a){v("failed to asynchronously prepare wasm: "+a);t(a)})}if("object"!==typeof WebAssembly)return v("no native wasm support detected"),!1;if(!(e.wasmMemory instanceof WebAssembly.Memory))return v("no native wasm Memory in use"),!1;a.memory=e.wasmMemory;var f={global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,env:a,asm2wasm:ia,parent:e};E++;e.monitorRunDependencies&&e.monitorRunDependencies(E);if(e.instantiateWasm)try{return e.instantiateWasm(f,b)}catch(g){return v("Module.instantiateWasm callback failed with error: "+
g),!1}e.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||Ha()||"function"!==typeof fetch?d(c):WebAssembly.instantiateStreaming(fetch(G,{credentials:"same-origin"}),f).then(c,function(a){v("wasm streaming compile failed: "+a);v("falling back to ArrayBuffer instantiation");d(c)});return{}}e.reallocBuffer=function(a){0<a%65536&&(a+=65536-a%65536);var b=e.buffer.byteLength;try{var c=-1!==e.wasmMemory.grow((a-b)/65536)?e.buffer=e.wasmMemory.buffer:null}catch(d){c=null}return c};
e.asm=function(a,b){if(!b.table){a=e.wasmTableSize;var c=e.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==c?new WebAssembly.Table({initial:a,maximum:c,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);e.wasmTable=b.table}b.__memory_base||(b.__memory_base=e.STATIC_BASE);b.__table_base||(b.__table_base=0);return La(b)};va=1024;za.push({ib:function(){Ma()}});e.STATIC_BASE=va;e.STATIC_BUMP=12608;var H={};
function Na(a){if(Na.ya){var b=w[a>>2];var c=w[b>>2]}else Na.ya=!0,H.USER=H.LOGNAME="web_user",H.PATH="/",H.PWD="/",H.HOME="/home/web_user",H.LANG="C.UTF-8",H._=e.thisProgram,c=Da?Oa(1024):fa(1024),b=Da?Oa(256):fa(256),w[b>>2]=c,w[a>>2]=b;a=[];var d=0,f;for(f in H)if("string"===typeof H[f]){var g=f+"="+H[f];a.push(g);d+=g.length}if(1024<d)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(f=0;f<a.length;f++){d=g=a[f];for(var k=c,p=0;p<d.length;++p)A[k++>>0]=d.charCodeAt(p);A[k>>0]=0;w[b+
4*f>>2]=c;c+=g.length+1}w[b+4*a.length>>2]=0}function Pa(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Qa(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Pa(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Ra(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Sa(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function Ta(){var a=Array.prototype.slice.call(arguments,0);return Qa(a.join("/"))}function I(a,b){return Qa(a+"/"+b)}
function Ua(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Pa(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var Va=[];function Wa(a,b){Va[a]={input:[],output:[],za:b};Xa(a,Ya)}
var Ya={open:function(a){var b=Va[a.node.rdev];if(!b)throw new J(K.Ga);a.tty=b;a.seekable=!1},close:function(a){a.tty.za.flush(a.tty)},flush:function(a){a.tty.za.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.za.Xa)throw new J(K.Oa);for(var f=0,g=0;g<d;g++){try{var k=a.tty.za.Xa(a.tty)}catch(p){throw new J(K.Ma);}if(void 0===k&&0===f)throw new J(K.ab);if(null===k||void 0===k)break;f++;b[c+g]=k}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.za.Ka)throw new J(K.Oa);
try{for(var f=0;f<d;f++)a.tty.za.Ka(a.tty,b[c+f])}catch(g){throw new J(K.Ma);}d&&(a.node.timestamp=Date.now());return f}},Za={Xa:function(a){if(!a.input.length){var b=null;if(q){var c=new Buffer(256),d=0,f=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{f=fs.openSync("/dev/stdin","r"),g=!0}catch(k){}}try{d=fs.readSync(f,c,0,256,null)}catch(k){if(-1!=k.toString().indexOf("EOF"))d=0;else throw k;}g&&fs.closeSync(f);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;c=Array(ta(b)+1);b=oa(b,c,0,c.length);c.length=b;a.input=c}return a.input.shift()},Ka:function(a,b){null===b||10===b?(ea(D(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ea(D(a.output,0)),a.output=[])}},$a={Ka:function(a,b){null===b||10===b?(v(D(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},
flush:function(a){a.output&&0<a.output.length&&(v(D(a.output,0)),a.output=[])}},L={ta:null,qa:function(){return L.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new J(K.fb);L.ta||(L.ta={dir:{node:{ua:L.na.ua,sa:L.na.sa,lookup:L.na.lookup,Ca:L.na.Ca,rename:L.na.rename,unlink:L.na.unlink,rmdir:L.na.rmdir,readdir:L.na.readdir,symlink:L.na.symlink},stream:{va:L.oa.va}},file:{node:{ua:L.na.ua,sa:L.na.sa},stream:{va:L.oa.va,read:L.oa.read,write:L.oa.write,
Pa:L.oa.Pa,Ya:L.oa.Ya,$a:L.oa.$a}},link:{node:{ua:L.na.ua,sa:L.na.sa,readlink:L.na.readlink},stream:{}},Ra:{node:{ua:L.na.ua,sa:L.na.sa},stream:ab}});c=bb(a,b,c,d);16384===(c.mode&61440)?(c.na=L.ta.dir.node,c.oa=L.ta.dir.stream,c.ma={}):32768===(c.mode&61440)?(c.na=L.ta.file.node,c.oa=L.ta.file.stream,c.pa=0,c.ma=null):40960===(c.mode&61440)?(c.na=L.ta.link.node,c.oa=L.ta.link.stream):8192===(c.mode&61440)&&(c.na=L.ta.Ra.node,c.oa=L.ta.Ra.stream);c.timestamp=Date.now();a&&(a.ma[b]=c);return c},jb:function(a){if(a.ma&&
a.ma.subarray){for(var b=[],c=0;c<a.pa;++c)b.push(a.ma[c]);return b}return a.ma},zd:function(a){return a.ma?a.ma.subarray?a.ma.subarray(0,a.pa):new Uint8Array(a.ma):new Uint8Array},Sa:function(a,b){a.ma&&a.ma.subarray&&b>a.ma.length&&(a.ma=L.jb(a),a.pa=a.ma.length);if(!a.ma||a.ma.subarray){var c=a.ma?a.ma.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.ma,a.ma=new Uint8Array(b),0<a.pa&&a.ma.set(c.subarray(0,a.pa),0))}else for(!a.ma&&0<b&&(a.ma=[]);a.ma.length<b;)a.ma.push(0)},
mb:function(a,b){if(a.pa!=b)if(0==b)a.ma=null,a.pa=0;else{if(!a.ma||a.ma.subarray){var c=a.ma;a.ma=new Uint8Array(new ArrayBuffer(b));c&&a.ma.set(c.subarray(0,Math.min(b,a.pa)))}else if(a.ma||(a.ma=[]),a.ma.length>b)a.ma.length=b;else for(;a.ma.length<b;)a.ma.push(0);a.pa=b}},na:{ua:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.pa:40960===(a.mode&61440)?b.size=
a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.wa=4096;b.blocks=Math.ceil(b.size/b.wa);return b},sa:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&L.mb(a,b.size)},lookup:function(){throw cb[K.cb];},Ca:function(a,b,c,d){return L.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=db(b,c)}catch(g){}if(d)for(var f in d.ma)throw new J(K.Na);
}delete a.parent.ma[a.name];a.name=c;b.ma[c]=a;a.parent=b},unlink:function(a,b){delete a.ma[b]},rmdir:function(a,b){var c=db(a,b),d;for(d in c.ma)throw new J(K.Na);delete a.ma[b]},readdir:function(a){var b=[".",".."],c;for(c in a.ma)a.ma.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=L.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new J(K.Aa);return a.link}},oa:{read:function(a,b,c,d,f){var g=a.node.ma;if(f>=a.node.pa)return 0;a=
Math.min(a.node.pa-f,d);assert(0<=a);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.ma||a.ma.subarray)){if(g)return a.ma=b.subarray(c,c+d),a.pa=d;if(0===a.pa&&0===f)return a.ma=new Uint8Array(b.subarray(c,c+d)),a.pa=d;if(f+d<=a.pa)return a.ma.set(b.subarray(c,c+d),f),d}L.Sa(a,f+d);if(a.ma.subarray&&b.subarray)a.ma.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.ma[f+
g]=b[c+g];a.pa=Math.max(a.pa,f+d);return d},va:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.pa);if(0>b)throw new J(K.Aa);return b},Pa:function(a,b,c){L.Sa(a.node,b+c);a.node.pa=Math.max(a.node.pa,b+c)},Ya:function(a,b,c,d,f,g,k){if(32768!==(a.node.mode&61440))throw new J(K.Ga);c=a.node.ma;if(k&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<f||f+d<a.node.pa)c.subarray?c=c.subarray(f,f+d):c=Array.prototype.slice.call(c,f,f+d);a=!0;d=Oa(d);if(!d)throw new J(K.eb);b.set(c,
d)}else a=!1,d=c.byteOffset;return{Ad:d,yd:a}},$a:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new J(K.Ga);if(f&2)return 0;L.oa.write(a,b,0,d,c,!1);return 0}}},M={Ea:!1,ob:function(){M.Ea=!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);M.Ta={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},Qa:function(a){return Buffer.ya?Buffer.from(a):new Buffer(a)},qa:function(a){assert(q);return M.createNode(null,
"/",M.Wa(a.Ja.root),0)},createNode:function(a,b,c){if(16384!==(c&61440)&&32768!==(c&61440)&&40960!==(c&61440))throw new J(K.Aa);a=bb(a,b,c);a.na=M.na;a.oa=M.oa;return a},Wa:function(a){try{var b=fs.lstatSync(a);M.Ea&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;throw new J(K[c.code]);}return b.mode},ra:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.qa.Ja.root);b.reverse();return Ta.apply(null,b)},hb:function(a){a&=-2656257;var b=0,c;for(c in M.Ta)a&c&&(b|=
M.Ta[c],a^=c);if(a)throw new J(K.Aa);return b},na:{ua:function(a){a=M.ra(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new J(K[c.code]);}M.Ea&&!b.wa&&(b.wa=4096);M.Ea&&!b.blocks&&(b.blocks=(b.size+b.wa-1)/b.wa|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,wa:b.wa,blocks:b.blocks}},sa:function(a,b){var c=M.ra(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&
fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new J(K[d.code]);}},lookup:function(a,b){var c=I(M.ra(a),b);c=M.Wa(c);return M.createNode(a,b,c)},Ca:function(a,b,c,d){a=M.createNode(a,b,c,d);b=M.ra(a);try{16384===(a.mode&61440)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(f){if(!f.code)throw f;throw new J(K[f.code]);}return a},rename:function(a,b,c){a=M.ra(a);b=I(M.ra(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new J(K[d.code]);}},unlink:function(a,
b){a=I(M.ra(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new J(K[c.code]);}},rmdir:function(a,b){a=I(M.ra(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new J(K[c.code]);}},readdir:function(a){a=M.ra(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new J(K[b.code]);}},symlink:function(a,b,c){a=I(M.ra(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new J(K[d.code]);}},readlink:function(a){var b=M.ra(a);try{return b=fs.readlinkSync(b),b=
eb.relative(eb.resolve(a.qa.Ja.root),b)}catch(c){if(!c.code)throw c;throw new J(K[c.code]);}}},oa:{open:function(a){var b=M.ra(a.node);try{32768===(a.node.mode&61440)&&(a.Da=fs.openSync(b,M.hb(a.flags)))}catch(c){if(!c.code)throw c;throw new J(K[c.code]);}},close:function(a){try{32768===(a.node.mode&61440)&&a.Da&&fs.closeSync(a.Da)}catch(b){if(!b.code)throw b;throw new J(K[b.code]);}},read:function(a,b,c,d,f){if(0===d)return 0;try{return fs.readSync(a.Da,M.Qa(b.buffer),c,d,f)}catch(g){throw new J(K[g.code]);
}},write:function(a,b,c,d,f){try{return fs.writeSync(a.Da,M.Qa(b.buffer),c,d,f)}catch(g){throw new J(K[g.code]);}},va:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.Da).size}catch(d){throw new J(K[d.code]);}if(0>b)throw new J(K.Aa);return b}}},fb=null,gb={},N=[],hb=1,O=null,ib=!0,jb={},J=null,cb={};
function P(a,b){a=Ua("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Va:!0,La:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.La)throw new J(40);a=Pa(a.split("/").filter(function(a){return!!a}),!1);var f=fb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=db(f,a[d]);c=I(c,a[d]);f.Fa&&(!g||g&&b.Va)&&(f=f.Fa.root);if(!g||b.Ua)for(g=0;40960===(f.mode&61440);)if(f=kb(c),c=Ua(Ra(c),f),f=P(c,{La:b.La}).node,40<g++)throw new J(40);}return{path:c,node:f}}
function lb(a){for(var b;;){if(a===a.parent)return a=a.qa.Za,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function mb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%O.length}function nb(a){var b=mb(a.parent.id,a.name);a.lb=O[b];O[b]=a}function db(a,b){var c;if(c=(c=ob(a,"x"))?c:a.na.lookup?0:13)throw new J(c,a);for(c=O[mb(a.id,b)];c;c=c.lb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.na.lookup(a,b)}
function bb(a,b,c,d){Q||(Q=function(a,b,c,d){a||(a=this);this.parent=a;this.qa=a.qa;this.Fa=null;this.id=hb++;this.name=b;this.mode=c;this.na={};this.oa={};this.rdev=d},Q.prototype={},Object.defineProperties(Q.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}}));a=new Q(a,b,c,d);nb(a);return a}
var qb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function rb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function ob(a,b){if(ib)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 13}else return 13;return 0}function sb(a,b){try{return db(a,b),17}catch(c){}return ob(a,"wx")}
function tb(){var a=4096;for(var b=0;b<=a;b++)if(!N[b])return b;throw new J(24);}function ub(a){R||(R=function(){},R.prototype={},Object.defineProperties(R.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var b=new R,c;for(c in a)b[c]=a[c];a=b;b=tb();a.fd=b;return N[b]=a}var ab={open:function(a){a.oa=gb[a.node.rdev].oa;a.oa.open&&a.oa.open(a)},va:function(){throw new J(29);}};function Xa(a,b){gb[a]={oa:b}}
function vb(a,b){var c="/"===b,d=!b;if(c&&fb)throw new J(16);if(!c&&!d){var f=P(b,{Va:!1});b=f.path;f=f.node;if(f.Fa)throw new J(16);if(16384!==(f.mode&61440))throw new J(20);}b={type:a,Ja:{},Za:b,kb:[]};a=a.qa(b);a.qa=b;b.root=a;c?fb=a:f&&(f.Fa=b,f.qa&&f.qa.kb.push(b))}function wb(a,b,c){var d=P(a,{parent:!0}).node;a=Sa(a);if(!a||"."===a||".."===a)throw new J(22);var f=sb(d,a);if(f)throw new J(f);if(!d.na.Ca)throw new J(1);return d.na.Ca(d,a,b,c)}function S(a){wb(a,16895,0)}
function xb(a,b,c){"undefined"===typeof c&&(c=b,b=438);wb(a,b|8192,c)}function yb(a,b){if(!Ua(a))throw new J(2);var c=P(b,{parent:!0}).node;if(!c)throw new J(2);b=Sa(b);var d=sb(c,b);if(d)throw new J(d);if(!c.na.symlink)throw new J(1);c.na.symlink(c,b,a)}function kb(a){a=P(a).node;if(!a)throw new J(2);if(!a.na.readlink)throw new J(22);return Ua(lb(a.parent),a.na.readlink(a))}
function zb(a,b,c){if(""===a)throw new J(2);if("string"===typeof b){var d=qb[b];if("undefined"===typeof d)throw Error("Unknown file open mode: "+b);b=d}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=Qa(a);try{f=P(a,{Ua:!(b&131072)}).node}catch(k){}}d=!1;if(b&64)if(f){if(b&128)throw new J(17);}else f=wb(a,c,0),d=!0;if(!f)throw new J(2);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new J(20);if(!d&&(c=f?40960===(f.mode&61440)?40:
16384===(f.mode&61440)&&("r"!==rb(b)||b&512)?21:ob(f,rb(b)):2))throw new J(c);if(b&512){c=f;var g;"string"===typeof c?g=P(c,{Ua:!0}).node:g=c;if(!g.na.sa)throw new J(1);if(16384===(g.mode&61440))throw new J(21);if(32768!==(g.mode&61440))throw new J(22);if(c=ob(g,"w"))throw new J(c);g.na.sa(g,{size:0,timestamp:Date.now()})}b&=-641;f=ub({node:f,path:lb(f),flags:b,seekable:!0,position:0,oa:f.oa,pb:[],error:!1});f.oa.open&&f.oa.open(f);!e.logReadFiles||b&1||(Ab||(Ab={}),a in Ab||(Ab[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{jb.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),jb.onOpenFile(a,g))}catch(k){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+k.message)}return f}function Bb(a){if(null===a.fd)throw new J(9);a.Ia&&(a.Ia=null);try{a.oa.close&&a.oa.close(a)}catch(b){throw b;}finally{N[a.fd]=null}a.fd=null}function Cb(a,b,c){if(null===a.fd)throw new J(9);if(!a.seekable||!a.oa.va)throw new J(29);a.position=a.oa.va(a,b,c);a.pb=[]}
function Db(){J||(J=function(a,b){this.node=b;this.nb=function(a){this.Ba=a};this.nb(a);this.message="FS error";this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},J.prototype=Error(),J.prototype.constructor=J,[2].forEach(function(a){cb[a]=new J(a);cb[a].stack="<generic error, no stack>"}))}var Eb;function Fb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function T(a,b,c){a=I("/dev",a);var d=Fb(!!b,!!c);Gb||(Gb=64);var f=Gb++<<8|0;Xa(f,{open:function(a){a.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(a,c,d,f){for(var g=0,k=0;k<f;k++){try{var p=b()}catch(Fa){throw new J(5);}if(void 0===p&&0===g)throw new J(11);if(null===p||void 0===p)break;g++;c[d+k]=p}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,d,f){for(var g=0;g<f;g++)try{c(b[d+g])}catch(u){throw new J(5);}f&&(a.node.timestamp=Date.now());return g}});
xb(a,d,f)}
var Gb,U={},Q,R,Ab,K={fb:1,cb:2,ld:3,$b:4,Ma:5,Oa:6,qb:7,Bc:8,bb:9,Gb:10,ab:11,vd:11,eb:12,rb:13,Tb:14,Nc:15,Eb:16,Sb:17,wd:18,Ga:19,Pc:20,bc:21,Aa:22,wc:23,oc:24,Tc:25,sd:26,Ub:27,Jc:28,kd:29,gd:30,pc:31,Zc:32,Pb:33,cd:34,Fc:42,Xb:43,Hb:44,dc:45,ec:46,fc:47,mc:48,td:49,zc:50,cc:51,Mb:35,Cc:37,xb:52,Ab:53,xd:54,xc:55,Bb:56,Cb:57,Nb:35,Db:59,Lc:60,Ac:61,pd:62,Kc:63,Gc:64,Hc:65,ed:66,Dc:67,ub:68,md:69,Ib:70,$c:71,rc:72,Qb:73,zb:74,Uc:76,yb:77,dd:78,hc:79,ic:80,lc:81,kc:82,jc:83,Mc:38,Na:39,sc:36,nc:40,
Vc:95,Yc:96,Lb:104,yc:105,vb:97,bd:91,Rc:88,Ic:92,hd:108,Kb:111,sb:98,Jb:103,vc:101,tc:100,qd:110,Vb:112,Wb:113,Zb:115,wb:114,Ob:89,qc:90,ad:93,jd:94,tb:99,uc:102,ac:106,Oc:107,rd:109,ud:87,Rb:122,nd:116,Sc:95,Ec:123,Yb:84,Wc:75,Fb:125,Qc:131,Xc:130,od:86},V=0;function X(){V+=4;return w[V-4>>2]}function Hb(){var a=N[X()];if(!a)throw new J(K.bb);return a}
function Y(a){if(0===a)return 0;a=D(C,a);if(!H.hasOwnProperty(a))return 0;Y.ya&&Ib(Y.ya);a=H[a];var b=ta(a)+1,c=Oa(b);c&&oa(a,A,c,b);Y.ya=c;return Y.ya}Db();O=Array(4096);vb(L,"/");S("/tmp");S("/home");S("/home/web_user");
(function(){S("/dev");Xa(259,{read:function(){return 0},write:function(a,b,f,g){return g}});xb("/dev/null",259);Wa(1280,Za);Wa(1536,$a);xb("/dev/tty",1280);xb("/dev/tty1",1536);if("undefined"!==typeof crypto){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else q?b=function(){return require("crypto").randomBytes(1)[0]}:b=function(){t("random_device")};T("random",b);T("urandom",b);S("/dev/shm");S("/dev/shm/tmp")})();S("/proc");S("/proc/self");S("/proc/self/fd");
vb({qa:function(){var a=bb("/proc/self","fd",16895,73);a.na={lookup:function(a,c){var b=N[+c];if(!b)throw new J(9);a={parent:null,qa:{Za:"fake"},na:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");
za.unshift(function(){if(!e.noFSInit&&!Eb){assert(!Eb,"FS.init was previously called. If you want to initialize later with custom parameters, remove any earlier calls (note that one is automatically added to the generated code)");Eb=!0;Db();e.stdin=e.stdin;e.stdout=e.stdout;e.stderr=e.stderr;e.stdin?T("stdin",e.stdin):yb("/dev/tty","/dev/stdin");e.stdout?T("stdout",null,e.stdout):yb("/dev/tty","/dev/stdout");e.stderr?T("stderr",null,e.stderr):yb("/dev/tty1","/dev/stderr");var a=zb("/dev/stdin","r");
assert(0===a.fd,"invalid handle for stdin ("+a.fd+")");a=zb("/dev/stdout","w");assert(1===a.fd,"invalid handle for stdout ("+a.fd+")");a=zb("/dev/stderr","w");assert(2===a.fd,"invalid handle for stderr ("+a.fd+")")}});Aa.push(function(){ib=!1});Ba.push(function(){Eb=!1;var a=e._fflush;a&&a(0);for(a=0;a<N.length;a++){var b=N[a];b&&Bb(b)}});za.unshift(function(){});Ba.push(function(){});if(q){var fs=require("fs"),eb=require("path");M.ob()}e.wasmTableSize=768;e.wasmMaxTableSize=768;
e.gb={o:t,D:wa,i:function(a,b){return z[a](b)},h:function(a,b,c){return z[a](b,c)},g:function(a,b,c,d){return z[a](b,c,d)},f:function(a,b,c,d,f){return z[a](b,c,d,f)},e:function(a,b,c,d,f,g){return z[a](b,c,d,f,g)},d:function(a,b,c,d,f,g,k,p,x,B,u){return z[a](b,c,d,f,g,k,p,x,B,u)},c:function(a,b){z[a](b)},b:function(a,b,c){z[a](b,c)},n:function(a,b,c,d){z[a](b,c,d)},m:function(a,b,c,d,f){z[a](b,c,d,f)},l:function(a,b,c,d,f,g){z[a](b,c,d,f,g)},k:function(a,b,c,d,f,g,k){z[a](b,c,d,f,g,k)},j:function(a,
b,c,d,f,g,k,p,x,B){z[a](b,c,d,f,g,k,p,x,B)},C:function(a,b,c,d){t("Assertion failed: "+D(C,a)+", at: "+[b?D(C,b):"unknown filename",c,d?D(C,d):"unknown function"])},B:Na,r:function(a){e.___errno_location&&(w[e.___errno_location()>>2]=a);return a},A:function(a,b){V=b;try{var c=Hb();X();var d=X(),f=X(),g=X();Cb(c,d,g);w[f>>2]=c.position;c.Ia&&0===d&&0===g&&(c.Ia=null);return 0}catch(k){return"undefined"!==typeof U&&k instanceof J||t(k),-k.Ba}},q:function(a,b){V=b;try{var c=Hb(),d=X();a:{var f=X();for(b=
a=0;b<f;b++){var g=c,k=w[d+8*b>>2],p=w[d+(8*b+4)>>2],x=void 0,B=A;if(0>p||0>x)throw new J(22);if(null===g.fd)throw new J(9);if(0===(g.flags&2097155))throw new J(9);if(16384===(g.node.mode&61440))throw new J(21);if(!g.oa.write)throw new J(22);g.flags&1024&&Cb(g,0,2);var u="undefined"!==typeof x;if(!u)x=g.position;else if(!g.seekable)throw new J(29);var W=g.oa.write(g,B,k,p,x,void 0);u||(g.position+=W);try{if(g.path&&jb.onWriteToFile)jb.onWriteToFile(g.path)}catch(Z){console.log("FS.trackingDelegate['onWriteToFile']('"+
path+"') threw an exception: "+Z.message)}var Fa=W;if(0>Fa){var pb=-1;break a}a+=Fa}pb=a}return pb}catch(Z){return"undefined"!==typeof U&&Z instanceof J||t(Z),-Z.Ba}},z:function(a,b){V=b;return 42},y:function(a,b){V=b;try{var c=Hb(),d=X(),f=X();a=A;if(0>f||0>g)throw new J(22);if(null===c.fd)throw new J(9);if(1===(c.flags&2097155))throw new J(9);if(16384===(c.node.mode&61440))throw new J(21);if(!c.oa.read)throw new J(22);b="undefined"!==typeof g;if(!b)var g=c.position;else if(!c.seekable)throw new J(29);
var k=c.oa.read(c,a,d,f,g);b||(c.position+=k);return k}catch(p){return"undefined"!==typeof U&&p instanceof J||t(p),-p.Ba}},x:function(a,b){V=b;try{var c=D(C,X()),d=X(),f=X();return zb(c,d,f).fd}catch(g){return"undefined"!==typeof U&&g instanceof J||t(g),-g.Ba}},p:function(a,b){V=b;try{var c=Hb();Bb(c);return 0}catch(d){return"undefined"!==typeof U&&d instanceof J||t(d),-d.Ba}},w:function(){return y},v:function(a,b,c){C.set(C.subarray(b,b+c),a)},u:function(){wa()},t:Y,s:function(a){var b=Date.now();
w[a>>2]=b/1E3|0;w[a+4>>2]=b%1E3*1E3|0;return 0},a:ha};var Jb=e.asm({},e.gb,buffer);e.asm=Jb;e._XML_ErrorString=function(){return e.asm.E.apply(null,arguments)};e._XML_ExpatVersion=function(){return e.asm.F.apply(null,arguments)};e._XML_FreeContentModel=function(){return e.asm.G.apply(null,arguments)};e._XML_GetCurrentColumnNumber=function(){return e.asm.H.apply(null,arguments)};e._XML_GetCurrentLineNumber=function(){return e.asm.I.apply(null,arguments)};
e._XML_GetErrorCode=function(){return e.asm.J.apply(null,arguments)};e._XML_Parse=function(){return e.asm.K.apply(null,arguments)};e._XML_ParserCreateNS=function(){return e.asm.L.apply(null,arguments)};e._XML_ParserFree=function(){return e.asm.M.apply(null,arguments)};e._XML_ParserReset=function(){return e.asm.N.apply(null,arguments)};e._XML_SetAttlistDeclHandler=function(){return e.asm.O.apply(null,arguments)};e._XML_SetCharacterDataHandler=function(){return e.asm.P.apply(null,arguments)};
e._XML_SetCommentHandler=function(){return e.asm.Q.apply(null,arguments)};e._XML_SetElementDeclHandler=function(){return e.asm.R.apply(null,arguments)};e._XML_SetEndCdataSectionHandler=function(){return e.asm.S.apply(null,arguments)};e._XML_SetEndDoctypeDeclHandler=function(){return e.asm.T.apply(null,arguments)};e._XML_SetEndElementHandler=function(){return e.asm.U.apply(null,arguments)};e._XML_SetEndNamespaceDeclHandler=function(){return e.asm.V.apply(null,arguments)};
e._XML_SetEntityDeclHandler=function(){return e.asm.W.apply(null,arguments)};e._XML_SetNotationDeclHandler=function(){return e.asm.X.apply(null,arguments)};e._XML_SetProcessingInstructionHandler=function(){return e.asm.Y.apply(null,arguments)};e._XML_SetReturnNSTriplet=function(){return e.asm.Z.apply(null,arguments)};e._XML_SetStartCdataSectionHandler=function(){return e.asm._.apply(null,arguments)};e._XML_SetStartDoctypeDeclHandler=function(){return e.asm.$.apply(null,arguments)};
e._XML_SetStartElementHandler=function(){return e.asm.aa.apply(null,arguments)};e._XML_SetStartNamespaceDeclHandler=function(){return e.asm.ba.apply(null,arguments)};e._XML_SetUserData=function(){return e.asm.ca.apply(null,arguments)};e._XML_SetXmlDeclHandler=function(){return e.asm.da.apply(null,arguments)};var Ma=e.___emscripten_environ_constructor=function(){return e.asm.ea.apply(null,arguments)};e.___errno_location=function(){return e.asm.fa.apply(null,arguments)};
var Ib=e._free=function(){return e.asm.ga.apply(null,arguments)},Oa=e._malloc=function(){return e.asm.ha.apply(null,arguments)},na=e.stackAlloc=function(){return e.asm.ja.apply(null,arguments)},ma=e.stackRestore=function(){return e.asm.ka.apply(null,arguments)},la=e.stackSave=function(){return e.asm.la.apply(null,arguments)};e.dynCall_vi=function(){return e.asm.ia.apply(null,arguments)};e.asm=Jb;
e.cwrap=function(a,b,c,d){c=c||[];var f=c.every(function(a){return"number"===a});return"string"!==b&&f&&!d?ka(a):function(){var d=c,f=arguments,p=ka(a),x=[],B=0;if(f)for(var u=0;u<f.length;u++){var W=qa[d[u]];W?(0===B&&(B=la()),x[u]=W(f[u])):x[u]=f[u]}d=p.apply(null,x);d="string"===b?ra(d):"boolean"===b?!!d:d;0!==B&&ma(B);return d}};e.Pointer_stringify=ra;
e.addFunction=function(a){for(var b=0;30>b;b++)if(!z[b])return z[b]=a,1+b;throw"Finished up all reserved function pointers. Use a higher value for RESERVED_FUNCTION_POINTERS.";};e.removeFunction=function(a){z[a-1]=null};function da(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}da.prototype=Error();da.prototype.constructor=da;F=function Kb(){e.calledRun||Lb();e.calledRun||(F=Kb)};
function Lb(){function a(){if(!e.calledRun&&(e.calledRun=!0,!ja)){Da||(Da=!0,xa(za));xa(Aa);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var a=e.postRun.shift();Ca.unshift(a)}xa(Ca)}}if(!(0<E)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ea();xa(ya);0<E||e.calledRun||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},
1);a()},1)):a())}}e.run=Lb;function t(a){if(e.onAbort)e.onAbort(a);void 0!==a?(ea(a),v(a),a=JSON.stringify(a)):a="";ja=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}e.abort=t;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();e.noExitRuntime=!0;Lb();
