name: Tests

on:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:
    branches: ['*']

jobs:
  build:

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Check coding standards
        if: matrix.node-version == '20.x' && matrix.os == 'ubuntu-latest'
        run: npm run lint
      - name: Test
        run: npm run coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
